In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
## Vars and params

nodes = 5
self_sim = 0.
no_sim = -10.
#s_mat = np.zeros((nodes, nodes))
s_mat = np.full((nodes, nodes), no_sim)

# fill S
for i in range(nodes):
    for j in range(nodes):
        if not i == j:
            p_put = np.random.rand()
            if p_put > 0.7:
                s_mat[i][j] = -1
            
np.fill_diagonal(s_mat, self_sim)
print(s_mat)

[[  0. -10. -10.  -1.  -1.]
 [-10.   0. -10. -10. -10.]
 [-10.  -1.   0. -10.  -1.]
 [-10. -10. -10.   0. -10.]
 [ -1. -10. -10. -10.   0.]]


In [3]:
## Update R

def updateR(r_mat, damping=0):
    for i in range(nodes):
        for k in range(nodes):
            v = a_mat[i, :] + s_mat[i, :]
            v[k] = -np.inf
            v[i]= -np.inf
            r_mat[i, k] = r_mat[i, k] * damping + (1 - damping) * (s_mat[i, k] - np.max(v))
            
    return r_mat

In [4]:
## Update A 

def updateA(a_mat, damping=0):
    for i in range(nodes):
        for k in range(nodes):
            a = np.array(r_mat[:, k]) # Select column k
            # a_matll indices but the diagonal
            if i != k:
                a[i] = -np.inf
                a[k] = - np.inf
                a[a < 0] = 0
                a_mat[i, k] = a_mat[i, k] * damping + (1 - damping) * min(0, r_mat[k, k] + a.sum())
            # The diagonal
            else:
                a[k] = -np.inf
                a[a < 0] = 0
                a_mat[k, k] = a_mat[k, k] * damping + (1 - damping) * a.sum()
                
    return a_mat

In [5]:
## Some simulations
r_mat = np.zeros_like(s_mat)
a_mat = np.zeros_like(s_mat)

print(s_mat)
print(r_mat)
r_mat = updateR(r_mat)
print(r_mat)

[[  0. -10. -10.  -1.  -1.]
 [-10.   0. -10. -10. -10.]
 [-10.  -1.   0. -10.  -1.]
 [-10. -10. -10.   0. -10.]
 [ -1. -10. -10. -10.   0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 1. -9. -9.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [-9.  0.  1. -9.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 9. -9. -9. -9.  1.]]
