In [1]:
import numpy as np
import scipy.sparse as sp

In [17]:
dim = 10
a = sp.dok_matrix((dim, dim), dtype=np.int8)
for i in range(dim):
    for j in range(dim):
        p_put = np.random.rand()
        if p_put <= 0.2:
            num = np.random.randint(dim)
            a[i, j] = num
            
print(a)
a_dense = a.todense()
print(a_dense)

  (0, 2)	6
  (0, 4)	5
  (0, 6)	3
  (1, 1)	7
  (1, 3)	9
  (1, 4)	3
  (1, 5)	9
  (2, 1)	7
  (2, 3)	5
  (3, 0)	9
  (3, 3)	5
  (3, 5)	9
  (3, 6)	4
  (4, 4)	2
  (4, 7)	5
  (5, 0)	4
  (5, 2)	1
  (5, 3)	9
  (5, 4)	5
  (5, 5)	4
  (6, 5)	5
  (6, 9)	2
  (8, 7)	3
  (9, 6)	8
  (9, 7)	5
[[0 0 6 0 5 0 3 0 0 0]
 [0 7 0 9 3 9 0 0 0 0]
 [0 7 0 5 0 0 0 0 0 0]
 [9 0 0 5 0 9 4 0 0 0]
 [0 0 0 0 2 0 0 5 0 0]
 [4 0 1 9 5 4 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 2]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 8 5 0 0]]
